import React from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Layout Admin Perplex",
  description: "Generated by create next app",
};
export default function Layout({ children }: { children: React.ReactNode }) {
  return <div>{children}</div>;
}
