import React from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Layout Auth Perplex",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <- Paréntesis de apertura
    <div className="grid grid-cols-2 h-screen">
      <div className="flex items-center justify-center">{children}</div>
      <div className="bg-cyan-200 w-full" />
    </div>
  ); // <- Paréntesis de cierre
}
