import React from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Layout Auth Perplex",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <- Paréntesis de apertura
    <div className="h-screen grid grid-cols-1 md:grid-cols-2">
      <div className="flex flex-col items-center justify-center">
        {children}
      </div>
      <div className="bg-violet-400 w-full" />
    </div>
  ); // <- Paréntesis de cierre
}
